title: "ASS Anfänger Kurs"
url: "http://galaxycats.github.com/ASS-Beginner"
description: "Maintains the demo source code, course material, like hand outs and demo-scripts for the ASS courses at the University of Applied Science Cologne."
